import type { GenerateResult, TestCase, ExportColumn, ExportFormat } from './types'

// ─── Column definitions (default set) ────────────────────────────────────────

export const DEFAULT_COLUMNS: ExportColumn[] = [
  { key: 'id',               label: 'Test Case ID',      description: 'Unique identifier (TC001…)',    jiraField: 'Summary',                        enabled: true,  required: true },
  { key: 'title',            label: 'Title / Summary',   description: 'One-line test case title',       jiraField: 'Summary',                        enabled: true,  required: true },
  { key: 'type',             label: 'Test Type',         description: 'positive / negative / edge',     jiraField: 'Labels',                         enabled: true },
  { key: 'priority',         label: 'Priority',          description: 'Critical / High / Medium / Low', jiraField: 'Priority',                       enabled: true },
  { key: 'preconditions',    label: 'Preconditions',     description: 'Setup state before test runs',   jiraField: 'Custom field (Preconditions)',    enabled: true },
  { key: 'gherkin',          label: 'BDD / Gherkin',     description: 'Given / When / Then steps',      jiraField: 'Description',                    enabled: true },
  { key: 'steps',            label: 'Test Steps',        description: 'Plain English numbered steps',   jiraField: 'Custom field (Test Steps)',       enabled: true },
  { key: 'expectedResult',   label: 'Expected Result',   description: 'What should happen after steps', jiraField: 'Custom field (Expected Result)',  enabled: true },
  { key: 'tags',             label: 'Labels / Tags',     description: 'Categorisation tags',            jiraField: 'Labels',                         enabled: true },
  { key: 'traceability',     label: 'Traceability',      description: 'Parent story / epic key',        jiraField: 'Epic Link',                      enabled: false },
  { key: 'automationStatus', label: 'Automation Status', description: 'Manual / To Automate / Automated', jiraField: 'Custom field (Automation Status)', enabled: false },
  { key: 'component',        label: 'Component',         description: 'JIRA component name',           jiraField: 'Components',                     enabled: false },
  { key: 'assignee',         label: 'Assignee',          description: 'JIRA username to assign to',    jiraField: 'Assignee',                       enabled: false },
  { key: 'sprint',           label: 'Sprint',            description: 'Sprint name or ID',             jiraField: 'Custom field (Sprint)',           enabled: false },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getCellValue(tc: TestCase, col: ExportColumn, parentKey: string): string {
  switch (col.key) {
    case 'id':               return tc.id
    case 'title':            return tc.title
    case 'type':             return tc.type
    case 'priority':         return tc.priority
    case 'preconditions':    return (tc.preconditions ?? []).join('\n')
    case 'gherkin':          return tc.gherkin ?? ''
    case 'steps':            return (tc.steps ?? []).join('\n')
    case 'expectedResult':   return tc.expectedResult ?? ''
    case 'tags':             return tc.tags.join(', ')
    case 'traceability':     return parentKey
    case 'automationStatus': return 'Manual'
    case 'component':        return ''
    case 'assignee':         return ''
    case 'sprint':           return ''
    default:                 return ''
  }
}

function escapeCsv(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

// ─── Feature file ─────────────────────────────────────────────────────────────

export function buildFeatureFile(result: GenerateResult, parentKey = ''): string {
  const lines: string[] = [
    `# Generated by AI Test Case Generator — atulsharma8790.github.io`,
    `# Suite: ${result.suiteName}`,
    `# Summary: ${result.summary}`,
    `# Generated: ${new Date().toISOString()}`,
    parentKey ? `# Traceability: ${parentKey}` : '',
    '',
    `Feature: ${result.suiteName}`,
    `  ${result.summary}`,
    '',
  ]

  for (const tc of result.testCases) {
    lines.push(`  # ${tc.id} | ${tc.type.toUpperCase()} | Priority: ${tc.priority}`)
    if (tc.preconditions?.length) {
      lines.push(`  # Preconditions: ${tc.preconditions.join('; ')}`)
    }
    if (tc.gherkin) {
      const indented = tc.gherkin.split('\n').map(l => `  ${l}`).join('\n')
      lines.push(indented)
    } else if (tc.steps?.length) {
      lines.push(`  Scenario: ${tc.title}`)
      tc.steps.forEach((s, i) => lines.push(`    ${i === 0 ? 'Given' : 'And'} ${s}`))
      if (tc.expectedResult) lines.push(`    Then ${tc.expectedResult}`)
    }
    lines.push(`  @${tc.tags.join(' @')}`)
    lines.push('')
  }

  return lines.filter(l => l !== null).join('\n')
}

// ─── Plain text ───────────────────────────────────────────────────────────────

export function buildTxt(result: GenerateResult, parentKey = ''): string {
  const lines: string[] = [
    `TEST SUITE: ${result.suiteName}`,
    `Summary: ${result.summary}`,
    parentKey ? `Traceability: ${parentKey}` : '',
    `Generated: ${new Date().toLocaleString()}`,
    `${'─'.repeat(60)}`,
    '',
  ]

  result.testCases.forEach((tc, i) => {
    lines.push(`${i + 1}. [${tc.id}] ${tc.title}`)
    lines.push(`   Type: ${tc.type} | Priority: ${tc.priority}`)
    if (tc.preconditions?.length) lines.push(`   Preconditions: ${tc.preconditions.join('; ')}`)
    if (tc.gherkin) {
      lines.push('')
      tc.gherkin.split('\n').forEach(l => lines.push(`   ${l}`))
    }
    if (tc.steps?.length) {
      lines.push('')
      tc.steps.forEach(s => lines.push(`   ${s}`))
      if (tc.expectedResult) lines.push(`   ✓ Expected: ${tc.expectedResult}`)
    }
    lines.push(`   Tags: ${tc.tags.map(t => `@${t}`).join(' ')}`)
    lines.push('')
  })

  return lines.join('\n')
}

// ─── CSV ─────────────────────────────────────────────────────────────────────

export function buildCsv(
  result: GenerateResult,
  enabledColumns: ExportColumn[],
  parentKey = ''
): string {
  // JIRA-compatible CSV: use jiraField as header so it can be directly imported
  const headers = enabledColumns.map(c =>
    // JIRA bulk import uses the JIRA field name as column header
    c.key === 'title' ? 'Summary' : c.jiraField
  )

  const rows: string[][] = [headers]

  for (const tc of result.testCases) {
    const row = enabledColumns.map(col => {
      let val = getCellValue(tc, col, parentKey)
      // JIRA expects issue type in first eligible column
      if (col.key === 'id') val = `[${tc.id}] ${tc.title}` // Summary = ID + title
      return val
    })
    rows.push(row)
  }

  // Prepend Issue Type column (always required for JIRA import)
  const withIssueType = rows.map((row, i) =>
    i === 0 ? ['Issue Type', ...row] : ['Test', ...row]
  )

  return withIssueType.map(row => row.map(escapeCsv).join(',')).join('\n')
}

// ─── Excel ────────────────────────────────────────────────────────────────────

export async function buildExcel(
  result: GenerateResult,
  enabledColumns: ExportColumn[],
  parentKey = ''
): Promise<Buffer> {
  const XLSX = await import('xlsx')

  // Sheet 1: Test Cases
  const headers = ['Issue Type', ...enabledColumns.map(c => c.jiraField)]
  const rows = result.testCases.map(tc => [
    'Test',
    ...enabledColumns.map(col => getCellValue(tc, col, parentKey)),
  ])

  const tcSheet = XLSX.utils.aoa_to_sheet([headers, ...rows])

  // Column widths
  tcSheet['!cols'] = headers.map((h, i) => ({
    wch: i === 0 ? 12 : Math.max(20, h.length + 5),
  }))

  // Freeze top row
  tcSheet['!freeze'] = { xSplit: 0, ySplit: 1 }

  // Sheet 2: Summary
  const summaryData = [
    ['Suite Name', result.suiteName],
    ['Summary', result.summary],
    ['Total Test Cases', result.testCases.length],
    ['Positive', result.coverageSummary.positive],
    ['Negative', result.coverageSummary.negative],
    ['Edge', result.coverageSummary.edge],
    ['Boundary', result.coverageSummary.boundary],
    ['Traceability', parentKey || 'N/A'],
    ['Generated', new Date().toLocaleString()],
    ['Generated by', 'AI Test Case Generator — atulsharma8790.github.io'],
  ]
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData)
  summarySheet['!cols'] = [{ wch: 24 }, { wch: 60 }]

  // Sheet 3: JIRA Import Instructions
  const instructionData = [
    ['HOW TO IMPORT INTO JIRA'],
    [''],
    ['Option A — Bulk CSV Import (Enterprise Firewall Safe)'],
    ['1. Download the CSV export from the "Export" menu'],
    ['2. In JIRA: Project Settings → Issue Import → Import from CSV'],
    ['3. Upload the CSV file and map columns to JIRA fields'],
    ['4. Review the import summary and confirm'],
    [''],
    ['Option B — Direct API Upload (requires JIRA access)'],
    ['1. Use the "Upload to JIRA" button in the app'],
    ['2. Enter your JIRA URL, email, and API token'],
    ['3. Select project, issue type, and parent story for traceability'],
    ['4. Click Upload — test cases are created with issue links automatically'],
    [''],
    ['Column Mapping Reference'],
    ['App Column', 'JIRA Field', 'Notes'],
    ...enabledColumns.map(c => [c.label, c.jiraField, c.description]),
  ]
  const instructionSheet = XLSX.utils.aoa_to_sheet(instructionData)
  instructionSheet['!cols'] = [{ wch: 30 }, { wch: 35 }, { wch: 50 }]

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, tcSheet, 'Test Cases')
  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary')
  XLSX.utils.book_append_sheet(wb, instructionSheet, 'Import Guide')

  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }))
}

// ─── Xray XML ─────────────────────────────────────────────────────────────────

export function buildXrayXml(result: GenerateResult, projectKey: string, parentKey = ''): string {
  const escape = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

  const testElements = result.testCases.map(tc => {
    const steps = tc.steps?.length
      ? tc.steps.map((s, i) => `
      <step>
        <index>${i + 1}</index>
        <action>${escape(s)}</action>
        <result>${i === (tc.steps!.length - 1) && tc.expectedResult ? escape(tc.expectedResult) : ''}</result>
      </step>`).join('')
      : tc.gherkin
        ? `<gherkin>${escape(tc.gherkin)}</gherkin>`
        : ''

    return `
  <test>
    <summary>${escape(`[${tc.id}] ${tc.title}`)}</summary>
    <testType>${tc.gherkin ? 'Cucumber' : 'Manual'}</testType>
    <priority>${tc.priority}</priority>
    <labels>${tc.tags.join(',')}</labels>
    ${parentKey ? `<requirement>${escape(parentKey)}</requirement>` : ''}
    <steps>${steps}</steps>
  </test>`
  }).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<tests project="${escape(projectKey)}">
  <!-- Generated by AI Test Case Generator — atulsharma8790.github.io -->
  <!-- Suite: ${escape(result.suiteName)} -->
  <!-- Generated: ${new Date().toISOString()} -->
${testElements}
</tests>`
}
