'use client'

import { useState } from 'react'
import { ArrowLeft, Copy, Check, Download, RefreshCw, Loader2, ChevronDown } from 'lucide-react'
import type { GenerateResult, TestCase, OutputFormat } from '@/lib/types'

const typeColors: Record<TestCase['type'], string> = {
  positive: '#10B981',
  negative: '#EF4444',
  edge: '#F59E0B',
  boundary: '#6366F1',
}

const priorityColors: Record<TestCase['priority'], string> = {
  critical: '#EF4444',
  high: '#F59E0B',
  medium: '#06B6D4',
  low: '#6B7F96',
}

function GherkinRenderer({ text }: { text: string }) {
  const lines = text.split('\n')
  return (
    <div className="gherkin-block">
      {lines.map((line, i) => {
        const trimmed = line.trim()
        const indent = line.length - line.trimStart().length
        const pad = ' '.repeat(indent)

        if (trimmed.startsWith('Feature:')) return <div key={i}>{pad}<span className="gherkin-feature">{trimmed}</span></div>
        if (trimmed.startsWith('Scenario:') || trimmed.startsWith('Scenario Outline:')) return <div key={i}>{pad}<span className="gherkin-scenario">{trimmed}</span></div>
        if (/^(Given|When|Then|And|But)\b/.test(trimmed)) {
          const keyword = trimmed.split(' ')[0]
          const rest = trimmed.slice(keyword.length)
          return <div key={i}>{pad}<span className="gherkin-keyword">{keyword}</span>{rest}</div>
        }
        return <div key={i}>{pad}{trimmed || ' '}</div>
      })}
    </div>
  )
}

function CopyButton({ text, size = 'sm' }: { text: string; size?: 'sm' | 'xs' }) {
  const [copied, setCopied] = useState(false)
  function copy() {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <button
      onClick={copy}
      className={`flex items-center gap-1 transition-colors ${size === 'xs' ? 'text-xs' : 'text-sm'} ${copied ? 'text-emerald-400' : 'text-[#7B8FA8] hover:text-white'}`}
    >
      {copied ? <Check size={13} /> : <Copy size={13} />}
      {copied ? 'Copied!' : 'Copy'}
    </button>
  )
}

interface Props {
  result: GenerateResult
  format: OutputFormat
  onBack: () => void
  onRegenerate: () => void
  loading: boolean
}

export function OutputPanel({ result, format, onBack, onRegenerate, loading }: Props) {
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set([result.testCases[0]?.id]))

  function toggleExpand(id: string) {
    setExpandedIds(prev => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }

  function expandAll() {
    setExpandedIds(new Set(result.testCases.map(tc => tc.id)))
  }

  function collapseAll() {
    setExpandedIds(new Set())
  }

  function buildFullExport(): string {
    const lines: string[] = [
      `# ${result.suiteName}`,
      `# Generated by AI Test Case Generator — atulsharma8790.github.io`,
      `# ${new Date().toLocaleString()}`,
      `# Summary: ${result.summary}`,
      '',
    ]
    result.testCases.forEach(tc => {
      lines.push(`## ${tc.id} — ${tc.title}`)
      lines.push(`# Type: ${tc.type} | Priority: ${tc.priority}`)
      if (tc.preconditions?.length) lines.push(`# Preconditions: ${tc.preconditions.join(', ')}`)
      if (tc.gherkin) lines.push('', tc.gherkin)
      if (tc.steps) {
        lines.push('', 'Steps:')
        tc.steps.forEach(s => lines.push(`  ${s}`))
        if (tc.expectedResult) lines.push(`Expected Result: ${tc.expectedResult}`)
      }
      lines.push('')
    })
    return lines.join('\n')
  }

  function downloadFeature() {
    const content = buildFullExport()
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${result.suiteName.toLowerCase().replace(/\s+/g, '-')}.feature`
    a.click()
    URL.revokeObjectURL(url)
  }

  const { coverageSummary: cs } = result
  const total = cs.positive + cs.negative + cs.edge + cs.boundary

  return (
    <div className="max-w-[1000px] mx-auto">
      {/* Top bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-sm text-[#7B8FA8] hover:text-white transition-colors"
        >
          <ArrowLeft size={15} />
          New requirement
        </button>
        <div className="flex items-center gap-2">
          <button onClick={expandAll} className="text-xs text-[#7B8FA8] hover:text-white transition-colors px-2 py-1">Expand all</button>
          <button onClick={collapseAll} className="text-xs text-[#7B8FA8] hover:text-white transition-colors px-2 py-1">Collapse all</button>
          <button
            onClick={downloadFeature}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#12121E] border border-white/[0.08] text-[#94A3B8] hover:text-white text-xs font-medium transition-all"
          >
            <Download size={13} />
            Download .feature
          </button>
          <CopyButton text={buildFullExport()} />
          <button
            onClick={onRegenerate}
            disabled={loading}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#6366F1] hover:bg-[#4F46E5] text-white text-xs font-medium transition-all disabled:opacity-50"
          >
            {loading ? <Loader2 size={13} className="animate-spin" /> : <RefreshCw size={13} />}
            Regenerate
          </button>
        </div>
      </div>

      {/* Summary card */}
      <div className="rounded-2xl bg-[#12121E] border border-white/[0.08] p-6 mb-6">
        <div className="flex flex-wrap items-start justify-between gap-4 mb-4">
          <div>
            <h2 className="text-white font-bold text-xl mb-1">{result.suiteName}</h2>
            <p className="text-[#7B8FA8] text-sm leading-relaxed max-w-2xl">{result.summary}</p>
          </div>
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
            <span className="text-emerald-400 font-bold text-lg">{result.testCases.length}</span>
            <span className="text-emerald-400 text-xs font-medium">test cases</span>
          </div>
        </div>

        {/* Coverage breakdown */}
        <div className="grid grid-cols-4 gap-3">
          {([
            ['positive', 'Positive', cs.positive],
            ['negative', 'Negative', cs.negative],
            ['edge', 'Edge', cs.edge],
            ['boundary', 'Boundary', cs.boundary],
          ] as const).map(([type, label, count]) => (
            <div key={type} className="rounded-xl p-3 text-center" style={{ background: `${typeColors[type]}10`, border: `1px solid ${typeColors[type]}25` }}>
              <div className="text-xl font-bold" style={{ color: typeColors[type] }}>{count}</div>
              <div className="text-xs text-[#7B8FA8] mt-0.5">{label}</div>
              <div className="text-xs mt-1" style={{ color: typeColors[type] }}>
                {total > 0 ? Math.round((count / total) * 100) : 0}%
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Test cases */}
      <div className="space-y-3">
        {result.testCases.map((tc, i) => {
          const isOpen = expandedIds.has(tc.id)
          return (
            <div
              key={tc.id}
              className="rounded-xl bg-[#12121E] overflow-hidden transition-all duration-200"
              style={{ border: `1px solid ${isOpen ? typeColors[tc.type] + '35' : 'rgba(255,255,255,0.07)'}` }}
            >
              <button
                className="w-full text-left px-5 py-4 flex items-center gap-4"
                onClick={() => toggleExpand(tc.id)}
              >
                {/* Index */}
                <span className="text-xs text-[#6B7F96] font-mono w-8 flex-shrink-0">{String(i + 1).padStart(2, '0')}</span>

                {/* Type badge */}
                <span
                  className="text-xs font-semibold px-2 py-0.5 rounded-md flex-shrink-0 uppercase tracking-wide"
                  style={{ background: `${typeColors[tc.type]}15`, color: typeColors[tc.type], border: `1px solid ${typeColors[tc.type]}30` }}
                >
                  {tc.type}
                </span>

                {/* Title */}
                <span className="text-white text-sm font-medium flex-1 text-left">{tc.title}</span>

                {/* Priority */}
                <span
                  className="text-xs font-medium px-2 py-0.5 rounded-md flex-shrink-0 hidden sm:block"
                  style={{ color: priorityColors[tc.priority], background: `${priorityColors[tc.priority]}12`, border: `1px solid ${priorityColors[tc.priority]}25` }}
                >
                  {tc.priority}
                </span>

                {/* Tags */}
                <div className="hidden lg:flex gap-1 flex-shrink-0">
                  {tc.tags.slice(0, 2).map(tag => (
                    <span key={tag} className="text-xs px-1.5 py-0.5 rounded bg-[#1E1E2E] text-[#7B8FA8]">#{tag}</span>
                  ))}
                </div>

                <ChevronDown
                  size={16}
                  className="text-[#6B7F96] flex-shrink-0 transition-transform duration-200"
                  style={{ transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)' }}
                />
              </button>

              {isOpen && (
                <div className="px-5 pb-5 border-t border-white/[0.05]">
                  <div className="pt-4 space-y-4">
                    {/* Preconditions */}
                    {tc.preconditions && tc.preconditions.length > 0 && (
                      <div>
                        <p className="text-xs font-semibold uppercase tracking-wider text-[#6B7F96] mb-2">Preconditions</p>
                        <ul className="space-y-1">
                          {tc.preconditions.map((p, j) => (
                            <li key={j} className="text-sm text-[#94A3B8] flex gap-2">
                              <span className="text-[#6B7F96] flex-shrink-0">·</span>
                              {p}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Gherkin */}
                    {tc.gherkin && (
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <p className="text-xs font-semibold uppercase tracking-wider text-[#6B7F96]">Gherkin / BDD</p>
                          <CopyButton text={tc.gherkin} size="xs" />
                        </div>
                        <div className="rounded-xl bg-[#0A0A0F] border border-white/[0.06] p-4">
                          <GherkinRenderer text={tc.gherkin} />
                        </div>
                      </div>
                    )}

                    {/* Plain steps */}
                    {tc.steps && tc.steps.length > 0 && (
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <p className="text-xs font-semibold uppercase tracking-wider text-[#6B7F96]">Test Steps</p>
                          <CopyButton text={tc.steps.join('\n') + (tc.expectedResult ? '\n\nExpected Result: ' + tc.expectedResult : '')} size="xs" />
                        </div>
                        <div className="rounded-xl bg-[#0A0A0F] border border-white/[0.06] p-4 space-y-1.5">
                          {tc.steps.map((step, j) => (
                            <p key={j} className="text-sm text-[#94A3B8] leading-relaxed">{step}</p>
                          ))}
                          {tc.expectedResult && (
                            <div className="mt-3 pt-3 border-t border-white/[0.06]">
                              <span className="text-xs font-semibold text-emerald-400">Expected Result: </span>
                              <span className="text-sm text-[#94A3B8]">{tc.expectedResult}</span>
                            </div>
                          )}
                        </div>
                      </div>
                    )}

                    {/* Tags */}
                    {tc.tags.length > 0 && (
                      <div className="flex flex-wrap gap-1.5">
                        {tc.tags.map(tag => (
                          <span key={tag} className="text-xs px-2 py-0.5 rounded-md bg-[#1E1E2E] border border-white/[0.06] text-[#7B8FA8]">@{tag}</span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
